"""add edgar_pre edgar_num edgar_tag tables

Revision ID: 2baee0a6feac
Revises: 0a14c8d388fa
Create Date: 2025-12-16 20:11:10.655891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2baee0a6feac'
down_revision: Union[str, None] = '0a14c8d388fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edgar_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('custom', sa.String(length=1), nullable=True),
    sa.Column('abstract', sa.String(length=1), nullable=True),
    sa.Column('datatype', sa.String(length=50), nullable=True),
    sa.Column('iord', sa.String(length=1), nullable=True),
    sa.Column('crdr', sa.String(length=1), nullable=True),
    sa.Column('tlabel', sa.String(length=512), nullable=True),
    sa.Column('doc', sa.Text(), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('source_quarter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edgar_tag_source', 'edgar_tag', ['source_year', 'source_quarter'], unique=False)
    op.create_index('idx_edgar_tag_tag', 'edgar_tag', ['tag'], unique=False)
    op.create_index('idx_edgar_tag_tag_version', 'edgar_tag', ['tag', 'version'], unique=False)
    op.create_table('edgar_num',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('adsh', sa.String(length=20), nullable=False),
    sa.Column('tag', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('ddate', sa.String(length=8), nullable=True),
    sa.Column('qtrs', sa.String(length=8), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('segments', sa.Text(), nullable=True),
    sa.Column('coreg', sa.String(length=256), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('footnote', sa.Text(), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('source_quarter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adsh'], ['filings.adsh'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edgar_num_adsh', 'edgar_num', ['adsh'], unique=False)
    op.create_index('idx_edgar_num_adsh_tag', 'edgar_num', ['adsh', 'tag'], unique=False)
    op.create_index('idx_edgar_num_ddate', 'edgar_num', ['ddate'], unique=False)
    op.create_index('idx_edgar_num_source', 'edgar_num', ['source_year', 'source_quarter'], unique=False)
    op.create_index('idx_edgar_num_tag', 'edgar_num', ['tag'], unique=False)
    op.create_table('edgar_pre',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('adsh', sa.String(length=20), nullable=False),
    sa.Column('report', sa.Integer(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('stmt', sa.String(length=2), nullable=True),
    sa.Column('inpth', sa.Integer(), nullable=True),
    sa.Column('rfile', sa.String(length=1), nullable=True),
    sa.Column('tag', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('plabel', sa.String(length=512), nullable=True),
    sa.Column('negating', sa.String(length=1), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('source_quarter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adsh'], ['filings.adsh'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edgar_pre_adsh', 'edgar_pre', ['adsh'], unique=False)
    op.create_index('idx_edgar_pre_adsh_stmt', 'edgar_pre', ['adsh', 'stmt'], unique=False)
    op.create_index('idx_edgar_pre_source', 'edgar_pre', ['source_year', 'source_quarter'], unique=False)
    op.create_index('idx_edgar_pre_tag', 'edgar_pre', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_edgar_pre_tag', table_name='edgar_pre')
    op.drop_index('idx_edgar_pre_source', table_name='edgar_pre')
    op.drop_index('idx_edgar_pre_adsh_stmt', table_name='edgar_pre')
    op.drop_index('idx_edgar_pre_adsh', table_name='edgar_pre')
    op.drop_table('edgar_pre')
    op.drop_index('idx_edgar_num_tag', table_name='edgar_num')
    op.drop_index('idx_edgar_num_source', table_name='edgar_num')
    op.drop_index('idx_edgar_num_ddate', table_name='edgar_num')
    op.drop_index('idx_edgar_num_adsh_tag', table_name='edgar_num')
    op.drop_index('idx_edgar_num_adsh', table_name='edgar_num')
    op.drop_table('edgar_num')
    op.drop_index('idx_edgar_tag_tag_version', table_name='edgar_tag')
    op.drop_index('idx_edgar_tag_tag', table_name='edgar_tag')
    op.drop_index('idx_edgar_tag_source', table_name='edgar_tag')
    op.drop_table('edgar_tag')
    # ### end Alembic commands ###
