"""drop fk constraints on edgar tables

Revision ID: 9b41cf14c95c
Revises: 5d342422cd5b
Create Date: 2025-12-17 00:48:17.695549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b41cf14c95c'
down_revision: Union[str, None] = '5d342422cd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('edgar_num_adsh_fkey', 'edgar_num', type_='foreignkey')
    op.drop_constraint('edgar_pre_adsh_fkey', 'edgar_pre', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('edgar_pre_adsh_fkey', 'edgar_pre', 'filings', ['adsh'], ['adsh'], ondelete='CASCADE')
    op.create_foreign_key('edgar_num_adsh_fkey', 'edgar_num', 'filings', ['adsh'], ['adsh'], ondelete='CASCADE')
    # ### end Alembic commands ###
