"""Initial schema: companies, filings, datasets

Revision ID: b2a01e0082ff
Revises: 
Create Date: 2025-11-17 11:54:36.261055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a01e0082ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('sic', sa.String(length=4), nullable=True),
    sa.Column('industry_description', sa.String(length=255), nullable=True),
    sa.Column('first_filing_date', sa.Date(), nullable=True),
    sa.Column('last_filing_date', sa.Date(), nullable=True),
    sa.Column('total_filings', sa.Integer(), nullable=True),
    sa.Column('forms_filed', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cik')
    )
    op.create_index('idx_companies_last_filing', 'companies', ['last_filing_date'], unique=False)
    op.create_index('idx_companies_name', 'companies', ['company_name'], unique=False)
    op.create_index('idx_companies_sic', 'companies', ['sic'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('dataset_type', sa.String(length=50), nullable=True),
    sa.Column('download_status', sa.String(length=20), nullable=True),
    sa.Column('download_started_at', sa.DateTime(), nullable=True),
    sa.Column('download_completed_at', sa.DateTime(), nullable=True),
    sa.Column('download_error', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('total_submissions', sa.Integer(), nullable=True),
    sa.Column('total_companies', sa.Integer(), nullable=True),
    sa.Column('total_tags', sa.Integer(), nullable=True),
    sa.Column('total_num_records', sa.Integer(), nullable=True),
    sa.Column('zip_file_path', sa.Text(), nullable=True),
    sa.Column('zip_file_size_mb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extracted_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_datasets_status', 'datasets', ['download_status', 'processing_status'], unique=False)
    op.create_index('idx_datasets_year_quarter', 'datasets', ['year', 'quarter'], unique=False)
    op.create_table('filings',
    sa.Column('adsh', sa.String(length=20), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=10), nullable=True),
    sa.Column('sic', sa.String(length=4), nullable=True),
    sa.Column('countryba', sa.String(length=2), nullable=True),
    sa.Column('stprba', sa.String(length=2), nullable=True),
    sa.Column('cityba', sa.String(length=50), nullable=True),
    sa.Column('zipba', sa.String(length=10), nullable=True),
    sa.Column('bas1', sa.String(length=255), nullable=True),
    sa.Column('accepted_timestamp', sa.DateTime(), nullable=True),
    sa.Column('prevrpt', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.Boolean(), nullable=True),
    sa.Column('instance', sa.String(length=100), nullable=True),
    sa.Column('nciks', sa.Integer(), nullable=True),
    sa.Column('aciks', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('source_quarter', sa.Integer(), nullable=False),
    sa.Column('source_dataset', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('adsh')
    )
    op.create_index('idx_filings_cik', 'filings', ['cik'], unique=False)
    op.create_index('idx_filings_company_form', 'filings', ['cik', 'form_type'], unique=False)
    op.create_index('idx_filings_filed_date', 'filings', ['filed_date'], unique=False)
    op.create_index('idx_filings_fiscal_year', 'filings', ['fiscal_year'], unique=False)
    op.create_index('idx_filings_form_type', 'filings', ['form_type'], unique=False)
    op.create_index('idx_filings_period_end', 'filings', ['period_end_date'], unique=False)
    op.create_index('idx_filings_source', 'filings', ['source_year', 'source_quarter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_filings_source', table_name='filings')
    op.drop_index('idx_filings_period_end', table_name='filings')
    op.drop_index('idx_filings_form_type', table_name='filings')
    op.drop_index('idx_filings_fiscal_year', table_name='filings')
    op.drop_index('idx_filings_filed_date', table_name='filings')
    op.drop_index('idx_filings_company_form', table_name='filings')
    op.drop_index('idx_filings_cik', table_name='filings')
    op.drop_table('filings')
    op.drop_index('idx_datasets_year_quarter', table_name='datasets')
    op.drop_index('idx_datasets_status', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('idx_companies_sic', table_name='companies')
    op.drop_index('idx_companies_name', table_name='companies')
    op.drop_index('idx_companies_last_filing', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
